<a href="https://colab.research.google.com/github/Gilbert228/mini_project_numpy/blob/main/Numpy_mini_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
data_file = "/content/drive/MyDrive/Colab Notebooks/Data processing /makeSenseOfCensus.csv"

In [ ]:
import numpy as np
data=np.genfromtxt(data_file,delimiter=",",skip_header=1)
#printing the data
print('\ndata:\n\n',data)
print('\ntype of data:\n\n', type(data))


data:

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]

type of data:

 <class 'numpy.ndarray'>


In [ ]:
# step 3
new_record=np.array([[50,9,4,1,0,0,40,0]])
data = np.concatenate((data,new_record),axis = 0)

In [ ]:
data

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

In [ ]:
# 1, indexing an entire column
age = np.array(data[:,0])
print(age)
max_age=age.max()
print(max_age)
min_age=age.min()
print(min_age)
age_mean=age.mean()
print(age_mean)
age_std=np.std(age)
print(age_std)

[39. 50. 38. ... 40. 39. 50.]
90.0
17.0
38.06293706293706
13.341478176165857


In [ ]:
#step 4
race=np.array(data[:,2])
print(race)
race_0 = race[race==0]
race_1 = race[race==1]
race_2 = race[ race==2]
race_3 = race[race==3]
race_4 = race[ race==4]
print(race_0)
print(race_1)

[4. 4. 4. ... 4. 4. 4.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1.]


In [ ]:
len_0=len(race_0)
print(len_0)
len_1=len(race_1)
len_2=len(race_2)
len_3=len(race_3)
len_4=len(race_4)
L=np.array([len_0,len_1,len_2,len_3,len_4])
print(L)
l_min=L.min()
print(l_min)
#the minority race is race_3
min_race=3

10
[ 10  27 110   6 848]
6


In [ ]:
#step 5
senior_citizen=age[age > 60]

working_hour = data[:,6]

working_hours_sum = np.sum(working_hour[age>60])

working_hours_sum

1917.0

In [ ]:
senior_citizen_len=len(senior_citizen)
print(senior_citizen_len)

61


In [ ]:
avg_working_hours=working_hours_sum/senior_citizen_len
print(avg_working_hours)
# Government policy is not followed since a person over the age of 60 should not work over 25 hours.

31.42622950819672


In [ ]:
#step 6
education_num=data[:,1]
high=education_num[education_num>10]
low=education_num[education_num<=10]
print(high ,'\n', low)

[13. 13. 13. 14. 14. 13. 13. 13. 12. 11. 14. 16. 13. 12. 13. 12. 13. 13.
 13. 14. 11. 11. 15. 13. 11. 13. 16. 13. 13. 12. 13. 14. 16. 11. 13. 16.
 12. 14. 13. 14. 13. 15. 11. 13. 13. 13. 13. 12. 12. 13. 12. 14. 11. 11.
 13. 13. 13. 14. 14. 12. 14. 11. 13. 13. 13. 13. 13. 14. 16. 13. 13. 14.
 14. 14. 13. 13. 13. 12. 13. 13. 11. 15. 13. 14. 13. 12. 12. 15. 13. 11.
 13. 13. 14. 14. 13. 12. 13. 14. 15. 13. 13. 13. 13. 13. 14. 13. 12. 12.
 12. 13. 14. 13. 14. 11. 13. 11. 14. 12. 11. 13. 11. 12. 13. 13. 13. 13.
 11. 14. 13. 13. 12. 13. 11. 14. 13. 12. 13. 13. 13. 13. 11. 14. 16. 13.
 14. 14. 13. 12. 14. 13. 12. 11. 12. 13. 13. 14. 13. 11. 13. 12. 13. 13.
 13. 12. 13. 13. 13. 11. 11. 11. 13. 13. 13. 14. 12. 15. 11. 13. 16. 11.
 13. 13. 13. 14. 14. 11. 16. 13. 12. 13. 13. 13. 13. 13. 15. 13. 13. 12.
 14. 14. 13. 13. 13. 15. 13. 11. 13. 13. 13. 13. 16. 16. 13. 16. 14. 14.
 12. 13. 11. 13. 14. 13. 12. 14. 14. 13. 13. 13. 16. 13. 13. 13. 11. 13.
 13. 13. 13. 13. 11. 11. 13. 13. 14. 11. 13. 13. 13

In [ ]:
income=data[:,7]
avg_pay_high=np.mean(income[education_num>10])
print(round(avg_pay_high*100,2))
avg_pay_low=np.mean(income[education_num<=10])
print(round(avg_pay_low*100,2))

42.81
13.65
